changesDir: .changes
unreleasedDir: unreleased
headerPath: header.tpl.md
versionHeaderPath: ""
changelogPath: CHANGELOG.md
components:
  - CORE
  - DAEMON
versionExt: md
versionFormat: '## {{.Version}} - {{.Time.Format "2006-01-02"}}'
kindFormat: '### {{.Kind}}'
changeFormat: >-
  * ({{.Component}}) [#{{.Custom.Issue}}](https://projekte.kosit.org/xdomea/werkzeuge/-/issues/{{.Custom.Issue}}) {{.Body}}
custom:
  - key: Issue
    type: int
    minInt: 1
kinds:
  - label: Added
  - label: Changed
  - label: Deprecated
  - label: Removed
  - label: Fixed
  - label: Security
