// Generated by delombok at Wed Apr 29 14:38:01 CEST 2026
package org.kosit.validator.api.compact;

/**
 * Enthält Informationen über den verwendeten Validator (Name und Version).
 */
public class ValidatorEngineInformation {
    private String name;
    private String version;

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getName() {
        return this.name;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getVersion() {
        return this.version;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setName(final String name) {
        this.name = name;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setVersion(final String version) {
        this.version = version;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public ValidatorEngineInformation() {
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public ValidatorEngineInformation(final String name, final String version) {
        this.name = name;
        this.version = version;
    }
}
