// Generated by delombok at Wed Apr 29 14:39:15 CEST 2026
/*
 * Copyright 2017-2022  Koordinierungsstelle für IT-Standards (KoSIT)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.kosit.validator.impl.tasks;

import org.kosit.validator.impl.ConversionService;
import org.kosit.validator.model.xvrl.XVRLReportSummary;

import jakarta.xml.bind.JAXBException;
import jakarta.xml.bind.Marshaller;
import jakarta.xml.bind.util.JAXBSource;
import net.sf.saxon.s9api.DocumentBuilder;
import net.sf.saxon.s9api.Processor;
import net.sf.saxon.s9api.SaxonApiException;
import net.sf.saxon.s9api.XdmNode;

public class XvrlSerializer {

    private final ConversionService conversionService;

    private final Processor processor;

    public XdmNode serialize(final XVRLReportSummary summary) throws JAXBException, SaxonApiException {
        final DocumentBuilder documentBuilder = this.processor.newDocumentBuilder();
        final Marshaller marshaller = this.conversionService.getJaxbContext().createMarshaller();
        final JAXBSource source = new JAXBSource(marshaller, summary);
        // wrap to circumvent inconsistency between sax and saxon
        source.setXMLReader(new ReaderWrapper(source.getXMLReader()));
        return documentBuilder.build(source);
    }

    public XvrlSerializer(final ConversionService conversionService, final Processor processor) {
        this.conversionService = conversionService;
        this.processor = processor;
    }
}
