validator:
  framework-version: 1.0.2
  logging:
    json: false
  scenarios:
    - scenarioPath: src/test/resources/examples/simple/scenarios.xml
      repositoryPath: src/test/resources/examples/simple/repository

quarkus:
  smallrye-openapi:
    store-schema-directory: target/openapi
  swagger-ui:
    path: /docs
    always-include: true
  log:
    console:
      json:
        enabled: ${validator.logging.json}
    level: INFO
  package:
    jar:
      type: uber-jar
  container-image:
    tag: ${quarkus.application.version}
    build: true
    push: false
