quarkus.smallrye-openapi.path=/openapi
quarkus.swagger-ui.path=/docs
quarkus.swagger-ui.always-include=true

validator.debugOutput=false
validator.debugLog=false
validator.logLevel=OFF
validator.scenarios[0].scenarioPath=src/test/resources/examples/simple/scenarios.xml
validator.scenarios[0].repositoryPath=src/test/resources/examples/simple/repository