// Generated by delombok at Wed Apr 29 14:36:40 CEST 2026
/*
 * Copyright 2017-2022  Koordinierungsstelle für IT-Standards (KoSIT)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.kosit.validator.cmd;

import static org.kosit.validator.impl.xvrl.XVRLReportBuilder.builder;
import static org.kosit.validator.impl.xvrl.XVRLReportBuilder.detection;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;

import org.kosit.validator.impl.ConversionService;
import org.kosit.validator.impl.model.ProcessStepResult;
import org.kosit.validator.impl.model.Result;
import org.kosit.validator.impl.tasks.CheckAction;
import org.kosit.validator.impl.tasks.CreateReportsAction;
import org.kosit.validator.impl.xvrl.XVRLReportBuilder;
import org.kosit.validator.model.xvrl.XVRLDetection;
import org.kosit.validator.model.xvrl.XVRLReport;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * Schreibt das Prüfergebnis als XML-Dokument an eine definierte Stelle.
 * 
 * @author Andreas Penski
 */
class SerializeReportAction implements CheckAction {

    private static final Logger log = LoggerFactory.getLogger(SerializeReportAction.class);

    public static final Process.Key<Boolean, String> KEY = new Process.Key<>(Boolean.class, String.class);

    private static final String REPORT_NAME = "Serialize Report";

    private final Path outputDirectory;

    private final ConversionService conversionService;

    private final NamingStrategy namingStrategy;

    private static XVRLReport generateXVRLReport(final Result<Boolean, String> result) {
        if (result.isValid()) {
            return builder(REPORT_NAME).add(detection().addMessage("Serialization successful").severity(XVRLDetection.Severity.INFO))
                    .build();
        }
        return XVRLReportBuilder.builder(REPORT_NAME).addAll(result.getErrors().stream().map(e -> detection().addError(e))).build();
    }

    @Override
    public ProcessStepResult<Boolean, String> check(final Process process) {
        final Path file = this.outputDirectory.resolve(this.namingStrategy.createName(process.getName()));
        try {
            log.info("Serializing result to {}", file.toAbsolutePath());
            final String xml = this.conversionService.writeXml(process.getXvrlReportSummary());
            Files.write(file, xml.getBytes());
        } catch (final IOException e) {
            log.error("Can not serialize result report to {}", file.toAbsolutePath(), e);
        }
        final ProcessStepResult<Boolean, String> processStepResult = new ProcessStepResult<>(KEY);
        final Result<Boolean, String> stepResult = new Result<>();
        processStepResult.setResult(stepResult);
        processStepResult.setReport(generateXVRLReport(stepResult));
        return processStepResult;
    }

    @Override
    public boolean isSkipped(final Process results) {
        if (results.getResult(CreateReportsAction.KEY) == null) {
            log.warn("Can not serialize result report. No document found");
            return true;
        }
        return false;
    }

    public SerializeReportAction(final Path outputDirectory, final ConversionService conversionService,
            final NamingStrategy namingStrategy) {
        this.outputDirectory = outputDirectory;
        this.conversionService = conversionService;
        this.namingStrategy = namingStrategy;
    }
}
