// Generated by delombok at Wed Apr 29 14:39:15 CEST 2026
/*
 * Copyright 2017-2022  Koordinierungsstelle für IT-Standards (KoSIT)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.kosit.validator.impl.input;

import static org.kosit.validator.impl.input.StreamHelper.drain;

import java.io.IOException;
import java.io.InputStream;

import org.kosit.validator.api.Input;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * Base class for all {@link Input Inputs}.
 * 
 * @author Andreas Penski
 */
public abstract class AbstractInput implements Input, LazyReadInput {

    private static final Logger log = LoggerFactory.getLogger(AbstractInput.class);

    private byte[] hashCode;

    private long length;

    @Override
    public byte[] getHashCode() {
        if (this.hashCode == null) {
            log.warn("Extra calculating hashcode. This is in-efficient in most cases");
            computeHashcode();
        }
        return this.hashCode;
    }

    protected void computeHashcode() {
        try {
            drain(this);
        } catch (final IOException e) {
            log.error("Error extra computing hashcode", e);
        }
    }

    protected InputStream wrap(final InputStream stream) {
        InputStream result = stream;
        if (!isHashcodeComputed()) {
            result = StreamHelper.wrapDigesting(this, result, getDigestAlgorithm());
        }
        if (getLength() == 0) {
            result = StreamHelper.wrapCount(this, result);
        }
        return result;
    }

    @Override
    public boolean isHashcodeComputed() {
        return this.hashCode != null;
    }

    @Override
    public void setHashCode(final byte[] digest) {
        this.hashCode = digest;
    }

    public boolean supportsMultipleReads() {
        return true;
    }

    public long getLength() {
        return this.length;
    }

    public void setLength(final long length) {
        this.length = length;
    }
}
