// Generated by delombok at Wed Apr 29 14:39:15 CEST 2026
/*
 * Copyright 2017-2022  Koordinierungsstelle für IT-Standards (KoSIT)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.kosit.validator.impl.input;

import java.io.ByteArrayInputStream;
import java.io.InputStream;

import javax.xml.transform.Source;
import javax.xml.transform.stream.StreamSource;

/**
 * Classical in-memory {@link org.kosit.validator.api.Input}. It is not memory efficient to read the whole file into
 * memory prio validating. Consider using the {@link ResourceInput}.
 * 
 * @author Andreas Penski
 */
public class ByteArrayInput extends AbstractInput {

    private final byte[] content;

    private final String name;

    private final String digestAlgorithm;

    @Override
    public long getLength() {
        return this.content != null ? this.content.length : 0;
    }

    @Override
    public Source getSource() {
        final InputStream stream = wrap(new ByteArrayInputStream(this.content));
        return new StreamSource(stream, getName());
    }

    public byte[] getContent() {
        return this.content;
    }

    public String getName() {
        return this.name;
    }

    public String getDigestAlgorithm() {
        return this.digestAlgorithm;
    }

    public ByteArrayInput(final byte[] content, final String name, final String digestAlgorithm) {
        this.content = content;
        this.name = name;
        this.digestAlgorithm = digestAlgorithm;
    }
}
