<?xml version="1.0" encoding="UTF-8"?>

<!--
  Schema for XML Validation Report Language; adapted from a proposal
  by Matthieu Ricaud incorporating some suggestions by Gerrit Imsieke
  See https://github.com/xproc/3.0-steps/issues/15
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
           elementFormDefault="qualified" 
           targetNamespace="http://www.xproc.org/ns/xvrl" 
           xmlns:xvrl="http://www.xproc.org/ns/xvrl">
  
  <xs:import namespace="http://www.w3.org/XML/1998/namespace" schemaLocation="xml.xsd"/>
  
  <xs:attributeGroup name="xmllang.attr">
    <xs:attribute ref="xml:lang" use="required"/>
  </xs:attributeGroup>
  <xs:attributeGroup name="xmlid.attr">
    <xs:attribute ref="xml:id" use="required"/>
  </xs:attributeGroup>
  <xs:attributeGroup name="xmlbase.attr">
    <xs:attribute ref="xml:base" use="required"/>
  </xs:attributeGroup>
  <!-- Default namespace URI for location XPaths: -->
  <xs:attributeGroup name="xpdns.attr">
    <xs:attribute name="xpath-default-namespace" use="required" type="xs:anyURI"/>
  </xs:attributeGroup>
  <xs:attributeGroup name="anyother.attr">
    <xs:anyAttribute processContents="skip"/>
  </xs:attributeGroup>
  <xs:attributeGroup name="any.attr">
    <xs:anyAttribute processContents="skip"/>
  </xs:attributeGroup>
  <xs:attributeGroup name="message.attr">
    <xs:anyAttribute processContents="skip"/>
  </xs:attributeGroup>
  <xs:attributeGroup name="common.attr">
    <xs:attribute ref="xml:lang"/>
    <xs:attribute ref="xml:id"/>
    <xs:attribute ref="xml:base"/>
    <xs:attribute name="xpath-default-namespace" type="xs:anyURI"/>
    <xs:attributeGroup ref="xvrl:anyother.attr"/>
  </xs:attributeGroup>
  <xs:attributeGroup name="href.attr">
    <xs:attribute name="href" use="required" type="xs:anyURI"/>
  </xs:attributeGroup>
  
  <xs:group name="any.element">
    <xs:choice>
      <xs:any namespace="##other" processContents="skip"/>
      <xs:any namespace="##local" processContents="skip"/>
    </xs:choice>
  </xs:group>
  
  <xs:complexType name="XvrlReportsType">
    <xs:sequence>
      <xs:element ref="xvrl:metadata"/>
      <xs:choice maxOccurs="unbounded">
        <xs:element ref="xvrl:report"/>
        <xs:element ref="xvrl:reports"/>
        <xs:element ref="xvrl:digest"/>
      </xs:choice>
    </xs:sequence>
    <xs:attributeGroup ref="xvrl:common.attr"/>
  </xs:complexType>
  <xs:element name="reports" type="xvrl:XvrlReportsType" />

  <xs:complexType name="XvrlReportType">
    <xs:sequence>
      <xs:element ref="xvrl:metadata"/>
      <xs:element ref="xvrl:detection" maxOccurs="unbounded" />
      <xs:element ref="xvrl:digest"/>
    </xs:sequence>
    <xs:attributeGroup ref="xvrl:common.attr"/>
  </xs:complexType>
  <xs:element name="report" type="xvrl:XvrlReportType" />
  
  <xs:complexType name="XvrlDigestType">
    <xs:attributeGroup ref="xvrl:common.attr"/>
    <xs:attribute name="valid">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="true"/>
          <xs:enumeration value="false"/>
          <xs:enumeration value="partial"/>
          <xs:enumeration value="undetermined"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="fatal-error-count" type="xs:integer"/>
    <xs:attribute name="error-count" type="xs:integer"/>
    <xs:attribute name="warning-count" type="xs:integer"/>
    <xs:attribute name="info-count" type="xs:integer"/>
    <xs:attribute name="unspecified-count" type="xs:integer"/>
    <xs:attribute name="fatal-error-codes">
      <xs:simpleType>
        <xs:list itemType="xs:token"/>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="error-codes">
      <xs:simpleType>
        <xs:list itemType="xs:token"/>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="warning-codes">
      <xs:simpleType>
        <xs:list itemType="xs:token"/>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="info-codes">
      <xs:simpleType>
        <xs:list itemType="xs:token"/>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="unspecified-codes">
      <xs:simpleType>
        <xs:list itemType="xs:token"/>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="worst">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="fatal-error"/>
          <xs:enumeration value="error"/>
          <xs:enumeration value="warning"/>
          <xs:enumeration value="info"/>
          <xs:enumeration value="nothing"/>
          <xs:enumeration value="unspecified"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
  </xs:complexType>
  <xs:element name="digest" type="xvrl:XvrlDigestType" />
  
  <xs:complexType name="XvrlMetadataType">
    <xs:choice minOccurs="0" maxOccurs="unbounded">
      <xs:element ref="xvrl:timestamp"/>
      <xs:element ref="xvrl:validator"/>
      <xs:element ref="xvrl:creator"/>
      <xs:element ref="xvrl:document"/>
      <xs:element ref="xvrl:title"/>
      <xs:element ref="xvrl:summary"/>
      <xs:element ref="xvrl:category"/>
      <xs:element ref="xvrl:schema"/>
      <xs:element ref="xvrl:supplemental"/>
    </xs:choice>
    <xs:attributeGroup ref="xvrl:common.attr"/>
  </xs:complexType>
  <xs:element name="metadata" type="xvrl:XvrlMetadataType" />
  
  <xs:complexType mixed="true" name="XvrlDocumentType">
    <xs:group minOccurs="0" ref="xvrl:any.element"/>
    <xs:attributeGroup ref="xvrl:common.attr"/>
    <xs:attribute name="href" type="xs:anyURI"/>
  </xs:complexType>
  <xs:element name="document" type="xvrl:XvrlDocumentType" />
  
  <xs:complexType name="XvrlDetectionType">
    <xs:choice minOccurs="0" maxOccurs="unbounded">
      <xs:element ref="xvrl:location"/>
      <xs:element ref="xvrl:provenance"/>
      <xs:element ref="xvrl:title"/>
      <xs:element ref="xvrl:summary"/>
      <xs:element ref="xvrl:category"/>
      <xs:choice>
        <xs:element ref="xvrl:let"/>
        <xs:element ref="xvrl:message"/>
      </xs:choice>
      <xs:element ref="xvrl:supplemental"/>
      <xs:element ref="xvrl:context"/>
    </xs:choice>
    <xs:attributeGroup ref="xvrl:common.attr"/>
    <xs:attribute name="severity">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="info"/>
          <xs:enumeration value="warning"/>
          <xs:enumeration value="error"/>
          <xs:enumeration value="fatal-error"/>
          <xs:enumeration value="unspecified"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="code"/>
  </xs:complexType>
  <xs:element name="detection" type="xvrl:XvrlDetectionType" />
  
  <xs:complexType mixed="true" name="XvrlLetType">
    <xs:group minOccurs="0" maxOccurs="unbounded" ref="xvrl:any.element"/>
    <xs:attributeGroup ref="xvrl:common.attr"/>
    <xs:attribute name="name" use="required" type="xs:QName"/>
    <xs:attribute name="value" type="xs:string"/>
  </xs:complexType>
  <xs:element name="let" type="xvrl:XvrlLetType" />
  
  <xs:attributeGroup name="location.model">
    <xs:attribute name="xpath-default-namespace" type="xs:anyURI"/>
    <xs:attribute name="xpath"/>
    <xs:attribute name="jsonpointer"/>
    <xs:attribute name="jsonpath"/>
    <xs:attribute name="href" type="xs:anyURI"/>
    <xs:attribute name="line" type="xs:positiveInteger"/>
    <xs:attribute name="column" type="xs:positiveInteger"/>
    <xs:attribute name="octet-position" type="xs:positiveInteger"/>
    <xs:attributeGroup ref="xvrl:anyother.attr"/>
  </xs:attributeGroup>
  
  <xs:complexType name="XvrlLocationType">
    <xs:attributeGroup ref="xvrl:location.model"/>
  </xs:complexType>
  <xs:element name="location" type="xvrl:XvrlLocationType" />
  
  <xs:complexType name="XvrlProvenanceType">
    <xs:sequence>
      <xs:element maxOccurs="unbounded" ref="xvrl:location"/>
    </xs:sequence>
  </xs:complexType>
  <xs:element name="provenance" type="xvrl:XvrlProvenanceType" />
  
  <xs:group name="value-of">
    <xs:sequence>
      <xs:element name="value-of">
        <xs:complexType>
          <xs:attribute name="name" use="required" type="xs:QName"/>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:group>
  
  <xs:group name="message.element">
    <xs:choice>
      <xs:element name="value-of">
        <xs:complexType mixed="true">
          <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:group ref="xvrl:message.element"/>
          </xs:choice>
          <xs:attributeGroup ref="xvrl:message.attr"/>
        </xs:complexType>
      </xs:element>
      <xs:any namespace="##other" processContents="skip"/>
      <xs:any namespace="##local" processContents="skip"/>
    </xs:choice>
  </xs:group>

  <xs:complexType mixed="true" name="XvrlMessageType">
    <xs:group minOccurs="0" maxOccurs="unbounded" ref="xvrl:message.element"/>
    <xs:attributeGroup ref="xvrl:common.attr"/>
  </xs:complexType>
  <xs:element name="message" type="xvrl:XvrlMessageType" />
  
  <xs:complexType mixed="true" name="XvrlSupplementalType">
    <xs:group minOccurs="0" maxOccurs="unbounded" ref="xvrl:any.element"/>
    <xs:attributeGroup ref="xvrl:common.attr"/>
  </xs:complexType>
  <xs:element name="supplemental" type="xvrl:XvrlSupplementalType" />

  <xs:complexType mixed="true" name="XvrlContextType">
    <xs:sequence>
      <xs:element minOccurs="0" ref="xvrl:location"/>
      <xs:group minOccurs="0" maxOccurs="unbounded" ref="xvrl:any.element"/>
    </xs:sequence>
    <xs:attributeGroup ref="xvrl:common.attr"/>
  </xs:complexType>
  <xs:element name="context" type="xvrl:XvrlContextType" />
  
  <xs:complexType mixed="true" name="XvrlValidatorType">
    <xs:group minOccurs="0" maxOccurs="unbounded" ref="xvrl:any.element"/>
    <xs:attributeGroup ref="xvrl:common.attr"/>
    <xs:attribute name="name" use="required"/>
    <xs:attribute name="version"/>
  </xs:complexType>
  <xs:element name="validator" type="xvrl:XvrlValidatorType" />
  
  <xs:complexType name="XvrlCreatorType">
    <xs:sequence>
      <xs:element minOccurs="0" ref="xvrl:invocation"/>
    </xs:sequence>
    <xs:attributeGroup ref="xvrl:common.attr"/>
    <xs:attribute name="name" use="required"/>
    <xs:attribute name="version"/>
  </xs:complexType>
  <xs:element name="creator" type="xvrl:XvrlCreatorType" />
  
  <xs:element name="invocation" type="xs:string"/>
  
  <xs:complexType name="XvrlSchemaType" mixed="true">
    <xs:group minOccurs="0" ref="xvrl:any.element"/>
    <xs:attributeGroup ref="xvrl:common.attr"/>
    <xs:attribute name="href" type="xs:anyURI"/>
    <xs:attribute name="schematypens" use="required" type="xs:anyURI"/>
    <xs:attribute name="version"/>
  </xs:complexType>
  <xs:element name="schema" type="xvrl:XvrlSchemaType" />
  
  <xs:complexType mixed="true" name="XvrlTitleType">
    <xs:group minOccurs="0" maxOccurs="unbounded" ref="xvrl:any.element"/>
    <xs:attributeGroup ref="xvrl:common.attr"/>
  </xs:complexType>
  <xs:element name="title" type="xvrl:XvrlTitleType" />
  
  <xs:complexType mixed="true" name="XvrlSummaryType">
    <xs:group minOccurs="0" maxOccurs="unbounded" ref="xvrl:any.element"/>
    <xs:attributeGroup ref="xvrl:common.attr"/>
  </xs:complexType>
  <xs:element name="summary" type="xvrl:XvrlSummaryType" />
  
  <xs:complexType mixed="true" name="XvrlCategoryType">
    <xs:group minOccurs="0" maxOccurs="unbounded" ref="xvrl:any.element"/>
    <xs:attributeGroup ref="xvrl:common.attr"/>
    <xs:attribute name="vocabulary" type="xs:token"/>
  </xs:complexType>
  <xs:element name="category" type="xvrl:XvrlCategoryType" />
  
  <xs:complexType name="XvrlTimestampType">
    <xs:simpleContent>
      <xs:extension base="xs:dateTime">
        <xs:attributeGroup ref="xvrl:common.attr"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:element name="timestamp" type="xvrl:XvrlTimestampType" />
</xs:schema>
