// Generated by delombok at Wed Apr 29 14:39:15 CEST 2026
/*
 * Copyright 2017-2022  Koordinierungsstelle für IT-Standards (KoSIT)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.kosit.validator.impl.model;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import org.kosit.validator.impl.tasks.CheckAction;
import org.kosit.validator.model.xvrl.XVRLReport;

public class ProcessStepResult<T, E> {
    private final CheckAction.Process.Key<T, E> key;
    private Result<T, E> result;
    private List<XVRLReport> report;

    public void setReport(final XVRLReport singleReport) {
        this.report = Collections.singletonList(singleReport);
    }

    public void addReports(final List<XVRLReport> collect) {
        if (collect != null) {
            if (this.report == null) {
                this.report = new ArrayList<>();
            }
            this.report.addAll(collect);
        }
    }

    public CheckAction.Process.Key<T, E> getKey() {
        return this.key;
    }

    public Result<T, E> getResult() {
        return this.result;
    }

    public List<XVRLReport> getReport() {
        return this.report;
    }

    public void setResult(final Result<T, E> result) {
        this.result = result;
    }

    public ProcessStepResult(final CheckAction.Process.Key<T, E> key) {
        this.key = key;
    }
}
