// Generated by delombok at Wed Apr 29 14:39:15 CEST 2026
/*
 * Copyright 2017-2022  Koordinierungsstelle für IT-Standards (KoSIT)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.kosit.validator.impl;

import org.kosit.validator.api.AcceptRecommendation;
import org.kosit.validator.api.Result;
import org.kosit.validator.api.XmlError;
import org.kosit.validator.impl.tasks.ReaderWrapper;
import org.kosit.validator.model.xvrl.XVRLReportSummary;
import jakarta.xml.bind.JAXBException;
import jakarta.xml.bind.Marshaller;
import jakarta.xml.bind.util.JAXBSource;
import net.sf.saxon.dom.NodeOverNodeInfo;
import net.sf.saxon.s9api.Processor;
import net.sf.saxon.s9api.SaxonApiException;
import net.sf.saxon.s9api.XdmNode;
import org.oclc.purl.dsdl.svrl.FailedAssert;
import org.oclc.purl.dsdl.svrl.SchematronOutput;
import org.w3c.dom.Document;
import java.util.Collections;
import java.util.List;
import java.util.stream.Collectors;

public class DefaultResult implements Result {
    /**
     * Die vom Validator erstelle interne Berichts-'Vorstufe'
     */
    private XVRLReportSummary reportSummary;
    /**
     * Das evaluierte Ergebnis.
     */
    private final AcceptRecommendation acceptRecommendation;
    private List<XmlError> schemaViolations;
    private List<SchematronOutput> schematronResult;
    private boolean processingSuccessful;
    private boolean wellformed;

    public DefaultResult(final AcceptRecommendation recommendation) {
        this.acceptRecommendation = recommendation;
    }

    @Override
    public XdmNode getReport() {
        final Marshaller marshaller;
        try {
            marshaller = new ConversionService().getJaxbContext().createMarshaller();
            final JAXBSource source = new JAXBSource(marshaller, getReportSummary());
            // wrap to circumvent inconsistency between sax and saxon
            source.setXMLReader(new ReaderWrapper(source.getXMLReader()));
            return new Processor(false).newDocumentBuilder().build(source);
        } catch (JAXBException | SaxonApiException e) {
            e.printStackTrace();
        }
        return null;
    }

    @Override
    public List<String> getProcessingErrors() {
        return reportSummary.getAllErrors();
    }

    /**
     * Gibt den Report als W3C-{@link Document} zurück.
     *
     * @return der Report
     */
    @Override
    public Document getReportDocument() {
        return (Document) NodeOverNodeInfo.wrap(getReport().getUnderlyingNode());
    }

    /**
     * Schnellzugriff auf die Empfehlung zur Weiterverarbeitung des Dokuments.
     *
     * @return true wenn {@link AcceptRecommendation#ACCEPTABLE}
     */
    @Override
    public boolean isAcceptable() {
        return isProcessingSuccessful() && AcceptRecommendation.ACCEPTABLE.equals(this.acceptRecommendation);
    }

    @Override
    public boolean isSchemaValid() {
        return getSchemaViolations() != null && getSchemaViolations().isEmpty();
    }

    /**
     * Gibt alle Schematron-Ergebnisse vom Typ {@link FailedAssert} zurück.
     *
     * @return die {@link FailedAssert}
     */
    @Override
    public List<FailedAssert> getFailedAsserts() {
        return getSchematronResult() != null ? getSchematronResult().stream().flatMap(e -> e.getActivePatternAndFiredRuleAndFailedAssert().stream()).filter(FailedAssert.class::isInstance).map(FailedAssert.class::cast).collect(Collectors.toList()) : Collections.emptyList();
    }

    private boolean isSchematronEvaluated() {
        return getSchematronResult() != null && getSchematronResult().stream().noneMatch(e -> e.getActivePatternAndFiredRuleAndFailedAssert().isEmpty());
    }

    @Override
    public boolean isSchematronValid() {
        return isSchematronEvaluated() && getFailedAsserts().isEmpty();
    }

    /**
     * Die vom Validator erstelle interne Berichts-'Vorstufe'
     */
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public XVRLReportSummary getReportSummary() {
        return this.reportSummary;
    }

    /**
     * Die vom Validator erstelle interne Berichts-'Vorstufe'
     */
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    void setReportSummary(final XVRLReportSummary reportSummary) {
        this.reportSummary = reportSummary;
    }

    /**
     * Das evaluierte Ergebnis.
     */
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public AcceptRecommendation getAcceptRecommendation() {
        return this.acceptRecommendation;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    void setSchemaViolations(final List<XmlError> schemaViolations) {
        this.schemaViolations = schemaViolations;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public List<XmlError> getSchemaViolations() {
        return this.schemaViolations;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public List<SchematronOutput> getSchematronResult() {
        return this.schematronResult;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    void setSchematronResult(final List<SchematronOutput> schematronResult) {
        this.schematronResult = schematronResult;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean isProcessingSuccessful() {
        return this.processingSuccessful;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setProcessingSuccessful(final boolean processingSuccessful) {
        this.processingSuccessful = processingSuccessful;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean isWellformed() {
        return this.wellformed;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setWellformed(final boolean wellformed) {
        this.wellformed = wellformed;
    }
}
