// Generated by delombok at Wed Apr 29 14:39:15 CEST 2026
/*
 * Copyright 2017-2022  Koordinierungsstelle für IT-Standards (KoSIT)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.kosit.validator.impl;

import java.util.ArrayList;
import java.util.List;
import java.util.Optional;
import javax.xml.validation.Schema;
import org.kosit.validator.api.ResolvingConfigurationStrategy;
import org.kosit.validator.model.scenarios.ResourceType;
import org.kosit.validator.model.scenarios.ScenarioType;
import net.sf.saxon.lib.ResourceResolver;
import net.sf.saxon.lib.UnparsedTextURIResolver;
import net.sf.saxon.s9api.XPathExecutable;
import net.sf.saxon.s9api.XPathSelector;
import net.sf.saxon.s9api.XsltExecutable;

/**
 * @author Andreas Penski
 */
public class Scenario {

    /**
     * Runtime objects for a transformation e.g. schematron or report.
     */
    public static class Transformation {
        private XsltExecutable executable;
        private ResourceType resourceType;

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public XsltExecutable getExecutable() {
            return this.executable;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public ResourceType getResourceType() {
            return this.resourceType;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public void setExecutable(final XsltExecutable executable) {
            this.executable = executable;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public void setResourceType(final ResourceType resourceType) {
            this.resourceType = resourceType;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Transformation(final XsltExecutable executable, final ResourceType resourceType) {
            this.executable = executable;
            this.resourceType = resourceType;
        }
    }

    private final ScenarioType configuration;
    private Schema schema;
    private boolean fallback;
    private XPathExecutable matchExecutable;
    private XPathExecutable acceptExecutable;
    private ResolvingConfigurationStrategy factory;
    private ResourceResolver uriResolver;
    private UnparsedTextURIResolver unparsedTextURIResolver;
    private List<Transformation> schematronValidations;
    private List<Transformation> reportTransformations;

    public List<Transformation> getReportTransformations() {
        if (this.reportTransformations == null) {
            this.reportTransformations = new ArrayList<>();
        }
        return this.reportTransformations;
    }

    public List<Transformation> getSchematronValidations() {
        if (this.schematronValidations == null) {
            this.schematronValidations = new ArrayList<>();
        }
        return this.schematronValidations;
    }

    public String getName() {
        return this.configuration.getName();
    }

    public XPathSelector getMatchSelector() {
        if (this.matchExecutable == null) {
            throw new IllegalStateException("No match executable supplied");
        }
        return this.matchExecutable.load();
    }

    /**
     * Returns a new XPath selector for evaluating the {@link org.kosit.validator.api.AcceptRecommendation}.
     *
     * @return new selector
     */
    public Optional<XPathSelector> getAcceptSelector() {
        final XPathSelector selector = this.acceptExecutable != null ? this.acceptExecutable.load() : null;
        return Optional.ofNullable(selector);
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Scenario(final ScenarioType configuration) {
        this.configuration = configuration;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setSchema(final Schema schema) {
        this.schema = schema;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setFallback(final boolean fallback) {
        this.fallback = fallback;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setMatchExecutable(final XPathExecutable matchExecutable) {
        this.matchExecutable = matchExecutable;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setAcceptExecutable(final XPathExecutable acceptExecutable) {
        this.acceptExecutable = acceptExecutable;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setFactory(final ResolvingConfigurationStrategy factory) {
        this.factory = factory;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setUriResolver(final ResourceResolver uriResolver) {
        this.uriResolver = uriResolver;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setUnparsedTextURIResolver(final UnparsedTextURIResolver unparsedTextURIResolver) {
        this.unparsedTextURIResolver = unparsedTextURIResolver;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setReportTransformations(final List<Transformation> reportTransformations) {
        this.reportTransformations = reportTransformations;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public ScenarioType getConfiguration() {
        return this.configuration;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Schema getSchema() {
        return this.schema;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean isFallback() {
        return this.fallback;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public XPathExecutable getMatchExecutable() {
        return this.matchExecutable;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public XPathExecutable getAcceptExecutable() {
        return this.acceptExecutable;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public ResolvingConfigurationStrategy getFactory() {
        return this.factory;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public ResourceResolver getUriResolver() {
        return this.uriResolver;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public UnparsedTextURIResolver getUnparsedTextURIResolver() {
        return this.unparsedTextURIResolver;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setSchematronValidations(final List<Transformation> schematronValidations) {
        this.schematronValidations = schematronValidations;
    }
}
