// Generated by delombok at Wed Apr 29 14:39:15 CEST 2026
package org.kosit.validator.impl;

import javax.xml.transform.dom.DOMSource;

import org.kosit.validator.api.SchematronCompiler;

import name.dmaus.schxslt.Compiler;
import name.dmaus.schxslt.adapter.SchXslt;
import net.sf.saxon.s9api.XsltExecutable;

/**
 * {@link SchematronCompiler} implementation backed by the original SchXslt XSLT-based Schematron processor (library
 * {@code name.dmaus.schxslt:schxslt}, version 1.10.1).
 *
 * <p>
 * This compiler delegates the actual transformation from Schematron schema ({@code .sch}) to XSLT stylesheet to the
 * {@link name.dmaus.schxslt.Compiler} class from the {@code schxslt-java} module, using the {@link SchXslt} adapter.
 * The resulting XSLT is returned as a {@link DOMSource} so that callers can compile it into an {@link XsltExecutable}
 * with Saxon.
 * </p>
 *
 * <p>
 * The class is effectively thread-safe: it holds a single, immutable {@link Compiler} instance, which in turn is
 * designed to be used safely from multiple threads.
 * </p>
 */
public class SchXsltCompiler extends AbstractSchXsltCompiler {
    public static final String COMPILER_ID = "schxslt";

    public SchXsltCompiler() {
        super(new Compiler(new SchXslt()));
    }

    @Override
    public String getId() {
        return SchXsltCompiler.COMPILER_ID;
    }
}
